Stuck.Web.Presentation/Controllers/LandingController.cs
using BasePresentation.Lookup;
using BasePresentation.Models;
using Stuck.API.Services;
using Stuck.BasePresentation.APIModels;
using Stuck.BasePresentation.Models;
using Stuck.Domain;
using Stuck.Services.Interfaces;
using Stuck.Web.Presentation.Helpers;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace Stuck.Web.Presentation.Controllers
{
    [AllowAnonymous]
    public class LandingController : BaseController
    {
        readonly IBaseRepository<BlockedPostCode> _postcodeRepository;
        readonly IStuckWebServices _stuckWebService;

        public LandingController(IStuckWebServices stuckWebService, IBaseRepository<BlockedPostCode> postcodeRepository)
        {
            _stuckWebService = stuckWebService;
            _postcodeRepository = postcodeRepository;
        }

        [HttpGet]
        public ActionResult Location()
        {
            Session["ServiceId"] = string.Empty;
            Session["bookingAddress"] = string.Empty;
            Session["destinationAddress"] = string.Empty;
            Session["serviceRegion"] = string.Empty;
            TempData["BookingProgress"] = null;
            TempData["continueConfirmJob"] = null;

            // get all post codes
            var postCodes = _postcodeRepository.GetAll().Select(a => a.PostCode).ToList<double>();
            var blockedPostCodes = string.Join(",", postCodes);

            return View(new BookingModel { GoogleMapKey = Generic_Contsants.GoogleMapKey, BlockedPostCodes = blockedPostCodes });
        }

        [HttpPost]
        public ActionResult Location(BookingModel bookingModel)
        {
            Session["bookingAddress"] = bookingModel.Address;
            return RedirectToAction("LandingScreen");
        }

        public ActionResult Home()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult LandingScreen()
        {
            var model = new LandingPageViewModel { GoogleMapKey = Generic_Contsants.GoogleMapKey };
            if (Session["bookingAddress"] != null && !string.IsNullOrEmpty(Session["bookingAddress"].ToString()))
            {
                model.Address = Session["bookingAddress"].ToString();
            }

            // get all post codes
            var postCodes = _postcodeRepository.GetAll().Select(a => a.PostCode).ToList<double>();
            var blockedPostCodes = string.Join(",", postCodes);
            model.BlockedPostCodes = blockedPostCodes;

            return View(model);
        }

        [AllowAnonymous]
        public JsonResult GetServicesForLocation(string Latitude, string Longtitude)
        {
            return Json(_stuckWebService.GetServicesForLocation(Latitude, Longtitude), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Battery()
        {
            return View();
        }


        public ActionResult FlatTyre()
        {
            return View();
        }

        public ActionResult EmptyFuel()
        {
            return View();
        }

        public ActionResult LockedOut()
        {
            return View();
        }

        public ActionResult Mechanical()
        {
            return View();
        }

        public ActionResult Tow()
        {
            return View();
        }

        public ActionResult FAQ()
        {
            return View();
        }

        public ActionResult Media()
        {
            return View();
        }

        public ActionResult Latest()
        {
            return View();
        }

        public ActionResult Supplier()
        {
            return View();
        }

        public ActionResult Legal()
        {
            return View();
        }

        public ActionResult Privacy()
        {
            return View();
        }

        public ActionResult Cookies()
        {
            return View();
        }

        public JsonResult SendEnquiryEmail(string Name, string Email, string Phone)
        {
            var ToEmail = ConfigurationManager.AppSettings["emailtosend"].ToString();
            var mailManagement = new MailManagement();
            string Body = string.Empty;
            Body = Body + "Hello Stuck Admin,<br/><br/>";
            Body = Body + "Enquiry is being received. Details are mentioned below<br/><br/>";
            Body = Body + "<b>Name : <b/>" + Name + "<br/><br/>";
            Body = Body + "<b>Email : <b/>" + Email + "<br/><br/>";
            Body = Body + "<b>Phone # : <b/>" + Phone + "<br/><br/>";
            Body = Body + "<b>Thank You,<b/><br/>";
            Body = Body + "Stuck Team";
            var result = mailManagement.SendMail(ToEmail, "Stuck Web - Enquiry Received", Body);
            return Json("", JsonRequestBehavior.AllowGet);
        }
    }

}

Stuck.Web.Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Stuck Web</title>
    <link rel="shortcut icon" href="~/images/favicon.png" type="image/x-icon" />
    <!-- For iPhone -->
    <link rel="apple-touch-icon-precomposed" href="~/images/Icon-App-60x60@3x.png">
    <!-- For iPhone 4 Retina display -->
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/images/iTunesArtwork@1x.png">
    <!-- For iPad -->
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/images/ic_launcher.png">
    <link href="https://fonts.googleapis.com/css?family=Ropa+Sans:400,400i" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-118571824-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());
        gtag('config', 'UA-118571824-1');
    </script>

</head>
<body class="mainBody fusion-body">
    @{ Html.EnableClientValidation(true); }

    <div class="navbar fusion-header navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @if (User.Identity.IsAuthenticated && !string.IsNullOrEmpty(User.Identity.Name) && Session["access_token"] != null && Session["Notifications"] != null)
                {
                    <div class="mob-noty">
                        <span class="icon-wrap">
                            <span class="noty-icon"><img src="~/images/149302.png" style="height:30px;"/></span>
                            <span id="notification_count">0</span>
                        </span>
                        <ul class="opn">
                            <li id="notification_li">
                                <div id="notificationContainer">
                                    <div id="notificationTitle">Notifications</div>
                                    <div id="notificationsBody" class="notifications"></div>
                                    <div id="notificationFooter"><a href="#">See All</a></div>
                                </div>
                            </li>
                        </ul>
                    </div>
                }

                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">
                    <img src="~/images/logo-white-1.png" />
                </a>
                @*@Html.ActionLink("Stuck", "LandingScreen", "Landing", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                @if (User.Identity.IsAuthenticated && !string.IsNullOrEmpty(User.Identity.Name) && Session["access_token"] != null)
                {
                    @*<ul class="nav navbar-nav">
                            <li>@Html.ActionLink("Booking Details", "Bookings", "Booking")</li>
                            <li>@Html.ActionLink("Vechile Details", "VehcileDetails", "Vehcile")</li>
                            <li>@Html.ActionLink("Profile", "CustomerProfile", "Account")</li>
                        </ul>*@
                }
                else
                {
                    <ul class="nav navbar-nav">
                        @*<li>@Html.ActionLink("Book Now !", "LandingScreen", "Landing")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    </ul>
                }
                <div class="pull-right">
                    @if (User.Identity.IsAuthenticated && !string.IsNullOrEmpty(User.Identity.Name) && Session["access_token"] != null)
                    {
                        var welcomestring = "welcome, " + HttpContext.Current.User.Identity.Name;
                        <ul class="nav navbar-nav">
                            <li id="notification_li">
                                <a href="#" id="notificationLink">Notifications</a>
                                <span id="notification_count">0</span>

                                <div id="notificationContainer">
                                    <div id="notificationTitle">Notifications</div>
                                    <div id="notificationsBody" class="notifications"></div>
                                    <div id="notificationFooter"><a href="#">See All</a></div>
                                </div>
                            </li>
                            <li>@Html.ActionLink(welcomestring, "CustomerProfile", "Account")</li>
                            <li>
                                @Html.ActionLink("Log Off", "Logout", "Account")
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("Sign In", "Authentication", "Account")</li>
                        </ul>
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="body-content clearfix">
        @RenderBody()
    </div>
    <footer class="fusion-footer-widget-area">
        <div class="container">
            <div class="mB15">
                <a style="display:inline-block" href="/"><img src="~/images/logo-white-1.png"></a>
            </div>
            <div class="row">
                <div class="col-sm-4 col-xs-6">
                    <div class="textwidget">
                        <a href="/Landing/Battery">Jump Start</a>
                        <a href="/Landing/FlatTyre">Flat Tyre</a>
                        <a href="/Landing/EmptyFuel">Empty Fuel</a>
                        <a href="/Landing/LockedOut">Locked Out</a>
                        <a href="/Landing/Mechanical">Mechanical</a>
                        <a href="/Landing/Tow">Tow Service</a>
                    </div>
                </div>
                <div class="col-sm-4 col-xs-6">
                    <div class="textwidget">
                        <a href="/Landing/FAQ">FAQ</a>
                        <a href="/Landing/Media">Media</a>
                        <a href="/Landing/Latest">Latest News</a>
                        <a href="mailto:hello@stuck.com.au">Contact Stuck</a>
                        <a href="/Landing/Supplier">Become A Stuck Service Provider</a>
                    </div>
                </div>
                <div class="col-sm-4 col-xs-12 badge_icons_footer">
                    <div class="textwidget">
                        <a href="https://itunes.apple.com/au/app/stuck-roadside-assistance/id1142911755?mt=8">
                            <img src="~/images/App-Store.png" alt="Download Stuck on the App Store" align="center" width="150">
                        </a>
                        <a href="https://play.google.com/store/apps/details?id=com.azimuthlabs.stuck">
                            <img src="~/images/google-play-badge.png" align="center" alt="Get Stuck on Google Play" width="150">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <footer class="fusion-footer-copyright-area fusion-footer-copyright-center">
        <div class="container">
            <div class="fusion-copyright-notice">
                <div>Copyright 2018 Azimuth Labs | Designed and Developed by <a target="_blank" href="http://www.media365.com.au">Media 365 </a> | <a href="/Landing/Legal">Legal</a> | <a href="/Landing/Privacy">Privacy</a> | <a href="/Landing/Cookies">Cookies</a></div>
            </div>
        </div>
    </footer>
    <div id="loader" class="loaderbg" style="display:none;">
        <div class="loader">
        </div>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script>
        $(window).load(function () {
            $(window).resize(function () {
                if ($(window).width() < 767) {
                    var sum = 0;
                    $('.choose_service_list > .box-outer > a').each(function () {
                        sum += $(this).outerWidth();
                    });
                    $('.choose_service_list > .box-outer').width(sum + 1);
                }
            }).resize();
        });



    </script>

    @if (User.Identity.IsAuthenticated && !string.IsNullOrEmpty(User.Identity.Name) && Session["access_token"] != null && Session["Notifications"] != null)
    {
        <script src="~/Scripts/custom.clientcalls.stuck.js"></script>
        <script>

            $(document).ready(function () {

                $(".icon-wrap").click(function () {
                    $('ul.opn').slideToggle();
                });

                $("#notificationLink").click(function () {
                    $("#notificationContainer").fadeToggle(300);
                    // $("#notification_count").fadeOut("slow");
                    return false;
                });



                //Document Click hiding the popup
                $(document).click(function () {
                    $("#notificationContainer").hide();
                });

                //Popup on click
                $("#notificationContainer").click(function () {
                    return false;
                });
            });

            setInterval(function () {
                getJobStatus();
            }, 8000);

            function getJobStatus() {
                GenericAjaxCall('GET', '/Notifications/GetCurrentJobState', "", onJobStatus);
            }

            function onJobStatus(model) {
                $("#notificationsBody").html(model.Message);
                $("#notification_count").html(model.Count)
                // console.log(model);
            }
        </script>
    }
</body>
</html>